test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Path: config/environments/production.rb

# amazon:
#   service: S3
#   access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
#   secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
#   region: <%= ENV['S3_REGION'] %>
#   bucket: <%= ENV['S3_BUCKET'] %>

azure:
  service: AzureStorage
  storage_account_name: <%= ENV['AZURE_STORAGE_ACCOUNT_NAME'] %>
  storage_access_key: <%= ENV['AZURE_STORAGE_ACCESS_KEY'] %>
  container: <%= ENV['AZURE_STORAGE_CONTAINER'] %>
  



